### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
sent=[    
    'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good'
]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

#### One Hot Representation

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

# Vocabulary size
voc_size = 10000

onehot_repr = [one_hot(words,voc_size) for words in sent] 
onehot_repr

[[1757, 6881, 9899, 2768],
 [1757, 6881, 9899, 2095],
 [1757, 7094, 9899, 4414],
 [5206, 8528, 6160, 9192, 1243],
 [5206, 8528, 6160, 9192, 2095],
 [556, 1757, 3207, 9899, 8570],
 [7375, 7001, 4203, 9192]]

### Word Embedding Represntation

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1757 6881 9899 2768]
 [   0    0    0    0 1757 6881 9899 2095]
 [   0    0    0    0 1757 7094 9899 4414]
 [   0    0    0 5206 8528 6160 9192 1243]
 [   0    0    0 5206 8528 6160 9192 2095]
 [   0    0    0  556 1757 3207 9899 8570]
 [   0    0    0    0 7375 7001 4203 9192]]


In [7]:
# 10 is neurons
# 8 is input length
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=8))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile('adam','mse')

In [9]:
# the input shape contains 7 sentences each of length 8
# so input shape is (None(7), 8)
# 8 is the input to neural network
# it contain 10 neurons
# the output shape is (8,10) for 1 sentence out of 7
# the total output shape is after predict function is (7, 8, 10)

In [10]:
# input shape is (7,8)
model.predict(embedded_docs).shape

(7, 8, 10)

In [11]:
model.predict(embedded_docs)[0].shape

(8, 10)

In [12]:
# visualizing the first output of predict function
model.predict(embedded_docs)[0]

array([[-0.02398672,  0.01787261,  0.04806561, -0.04361165, -0.00146826,
         0.02688828, -0.0486858 , -0.03266837,  0.01969441, -0.01591427],
       [-0.02398672,  0.01787261,  0.04806561, -0.04361165, -0.00146826,
         0.02688828, -0.0486858 , -0.03266837,  0.01969441, -0.01591427],
       [-0.02398672,  0.01787261,  0.04806561, -0.04361165, -0.00146826,
         0.02688828, -0.0486858 , -0.03266837,  0.01969441, -0.01591427],
       [-0.02398672,  0.01787261,  0.04806561, -0.04361165, -0.00146826,
         0.02688828, -0.0486858 , -0.03266837,  0.01969441, -0.01591427],
       [ 0.04674527, -0.04149848, -0.03498161, -0.01530217,  0.04261709,
         0.04094441,  0.04810598,  0.0027267 , -0.01100823, -0.00056242],
       [ 0.02613277, -0.04542097,  0.01615799, -0.02571359, -0.02070092,
         0.0152014 ,  0.03596845, -0.01894203, -0.02260681, -0.00656467],
       [-0.01264803, -0.00324515,  0.00425852, -0.04004061,  0.00293031,
         0.02006391, -0.03831049,  0.04479006

In [13]:
# the input is [   0    0    0    0 5704 8172 2978 1201] 
# each element in the input is converted into 10 elements
# total elements in the input is 8
# so the shape is (8, 10)
# in the above predicted doc first 4 arrays are same because these 4 arrays corresponds to 4 0's in the above input
# the above values we got after predict function all are trainable values